name: 'Build AUR Packages'
description: 'Identify and build missing packages'
runs:
  using: "composite"
  steps:
    - name: Prepare Builder User
      shell: bash
      run: |
        if ! id "builder" &>/dev/null; then
            useradd -m builder
            echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        fi
        chmod 777 .

    - name: Install Yay
      shell: bash
      run: |
        if ! command -v yay &> /dev/null; then
            su builder -c "
                git clone https://aur.archlinux.org/yay-bin.git /tmp/yay-bin
                cd /tmp/yay-bin
                makepkg -si --noconfirm
            "
        fi



    - name: Filter AUR vs Repo
      shell: bash
      run: |
        # Ensure sync
        pacman -Sy
        
        touch aur_deps.txt
        while read -r pkg; do
            [[ -z "$pkg" || "$pkg" =~ ^# ]] && continue
            if ! pacman -Si "$pkg" &> /dev/null; then
                echo "$pkg" >> aur_deps.txt
            fi
        done < iso-build/packages.x86_64
        
        echo "AUR Candidates:"
        cat aur_deps.txt

    - name: Build AUR
      shell: bash
      run: |
        mkdir -p repo
        chown builder:builder repo
        
        if [ -s aur_deps.txt ]; then
            echo "Building AUR packages..."
            su builder -c "
                mkdir -p /tmp/aur-build
                yay -S --noconfirm --builddir /tmp/aur-build \$(cat aur_deps.txt)
                find /tmp/aur-build -name '*.pkg.tar.zst' -exec cp {} repo/ \;
                cd repo
                repo-add endos-local.db.tar.gz *.pkg.tar.zst
            "
        else
            echo "No AUR deps found, creating empty repo"
            su builder -c "cd repo && repo-add endos-local.db.tar.gz"
        fi

    - name: Register Local Repo
      shell: bash
      run: |
        REPO_PATH="$(pwd)/repo"
        sed -i '1i[endos-local]\nSigLevel = Optional TrustAll\nServer = file://'"$REPO_PATH" iso-build/pacman.conf
