name: 'Prepare ISO Files'
description: 'Copy and setup ISO build files and dotfiles'
runs:
  using: "composite"
  steps:
    - name: Copy Releng Profile
      shell: bash
      run: |
        cp -r /usr/share/archiso/configs/releng iso-build

    - name: Inject Custom Files
      shell: bash
      run: |
        cp -a iso/airootfs/. iso-build/airootfs/

    - name: Copy Dotfiles
      shell: bash
      run: |
        rm -rf iso-build/airootfs/usr/share/endos/dots
        mkdir -p iso-build/airootfs/usr/share/endos/dots

        if [ -d "dots-hyprland-main" ]; then
            echo "Copying local dots-hyprland-main..."
            cp -a dots-hyprland-main/. iso-build/airootfs/usr/share/endos/dots/
        else
            echo "WARNING: Local dots not found, cloning..."
            git clone --recursive --depth 1 https://github.com/end-4/dots-hyprland.git iso-build/airootfs/usr/share/endos/dots
        fi
