name: 'Prepare ISO Files'
description: 'Copy and setup ISO build files and dotfiles'
runs:
  using: "composite"
  steps:
    - name: Copy Releng Profile
      shell: bash
      run: |
        cp -r /usr/share/archiso/configs/releng iso-build

    - name: Inject Custom Files
      shell: bash
      run: |
        cp -a iso/. iso-build/


