name: 'Configure EndOS ISO'
description: 'Final configuration, branding, and services'
runs:
  using: "composite"
  steps:
    - name: Configure Pacman
      shell: bash
      run: |
        # Enable Multilib
        if ! grep -q "^\[multilib\]" iso-build/pacman.conf; then
            echo "[multilib]" >> iso-build/pacman.conf
            echo "Include = /etc/pacman.d/mirrorlist" >> iso-build/pacman.conf
        fi
        # Enable Chaotic
        echo "" >> iso-build/pacman.conf
        echo "[chaotic-aur]" >> iso-build/pacman.conf
        echo "Include = /etc/pacman.d/chaotic-mirrorlist" >> iso-build/pacman.conf



    - name: Branding
      shell: bash
      run: |
        sed -i 's/iso_name="archlinux"/iso_name="EndOS"/' iso-build/profiledef.sh
        sed -i 's/iso_label="ARCH_$(date +%Y%m)"/iso_label="ENDOS_$(date +%Y%m)"/' iso-build/profiledef.sh
        sed -i 's/iso_publisher="Arch Linux <https:\/\/archlinux.org>"/iso_publisher="EndOS <https:\/\/github.com\/USBKayble\/EndOS>"/' iso-build/profiledef.sh
        sed -i 's/iso_application="Arch Linux Live\/Rescue CD"/iso_application="EndOS Live\/Rescue CD"/' iso-build/profiledef.sh

    - name: Configure Plymouth
      shell: bash
      run: |
        cat > iso-build/airootfs/etc/mkinitcpio.conf <<EOF
        MODULES=()
        BINARIES=()
        FILES=()
        HOOKS=(base udev plymouth modconf memdisk archiso archiso_loop_mnt archiso_pxe_common archiso_pxe_nbd archiso_pxe_http archiso_pxe_nfs archiso_kms block filesystems keyboard fsck)
        EOF

    - name: Configure Live User Env
      shell: bash
      run: |
        # Logs
        mkdir -p iso-build/airootfs/log
        chmod 777 iso-build/airootfs/log

        # Setup Command
        mkdir -p iso-build/airootfs/usr/local/bin

        
        # Permissions for static files are handled in profiledef.sh, 
        # but ensuring ownership here is a good safety net
        chown -R 0:0 iso-build/airootfs/root

        # Auto-login/start check
        # Archiso Releng uses ZSH by default for root.
        # We have a robust init script in .bash_profile (from iso/airootfs/root/.bash_profile)
        # We should make sure .zlogin uses it.
        LIVE_HOME="iso-build/airootfs/root"
        if [ -f "$LIVE_HOME/.bash_profile" ]; then
            echo "Converting .bash_profile to .zlogin for ZSH..."
            # ZSH is compatible enough for this script
            cp "$LIVE_HOME/.bash_profile" "$LIVE_HOME/.zlogin"
            # Ensure permissions
            chmod +x "$LIVE_HOME/.zlogin"
        else
            echo "WARNING: .bash_profile not found in root. Creating fallback .zlogin"
            echo "if [ -z \"\$DISPLAY\" ] && [ \"\$(tty)\" = \"/dev/tty1\" ]; then exec Hyprland; fi" >> "$LIVE_HOME/.zlogin"
        fi



    - name: Python Dependencies
      shell: bash
      run: |
        VENV_DIR="iso-build/airootfs/root/.local/state/quickshell/.venv"
        REQ_FILE="iso-build/requirements.txt"
        mkdir -p "$(dirname "$VENV_DIR")"
        
        export UV_NO_MODIFY_PATH=1
        uv venv "$VENV_DIR" --python 3.12
        
        if [ -f "$REQ_FILE" ]; then
            source "$VENV_DIR/bin/activate"
            uv pip install -r "$REQ_FILE"
            deactivate
        fi

    - name: Enable Services
      shell: bash
      run: |
        SERVICES_DIR="iso-build/airootfs/etc/systemd/system/multi-user.target.wants"
        mkdir -p "$SERVICES_DIR"
        
        # Disable Archiso default networkd/resolved to allow NetworkManager to take over
        rm -f "$SERVICES_DIR/systemd-networkd.service"
        rm -f "$SERVICES_DIR/systemd-resolved.service"
        rm -f "iso-build/airootfs/etc/systemd/system/dbus-org.freedesktop.resolve1.service"
        rm -f "iso-build/airootfs/etc/systemd/system/dbus-org.freedesktop.network1.service"
        
        # Enable NetworkManager
        ln -sf /usr/lib/systemd/system/NetworkManager.service "$SERVICES_DIR/NetworkManager.service"
        ln -sf /usr/lib/systemd/system/bluetooth.service "$SERVICES_DIR/bluetooth.service"
        ln -sf /usr/lib/systemd/system/sshd.service "$SERVICES_DIR/sshd.service"
        
        # DEBUG: Verify Root Files & Permissions
        echo "DEBUG: Listing /root to verify checks..."
        ls -la iso-build/airootfs/root/
        
        echo "DEBUG: Ensuring log permissions..."
        chown -R 0:0 iso-build/airootfs/log
        chmod 777 iso-build/airootfs/log

        # DEBUG: Verify Root Files
        echo "DEBUG: Listing /root to verify checks..."
        ls -la iso-build/airootfs/root/

    - name: Patch Boot Options
      shell: bash
      run: |
        find iso-build/syslinux -name "*.cfg" -exec sed -i 's/archisobasedir/splash quiet archisobasedir/g' {} +
        find iso-build/grub -name "grub.cfg" -exec sed -i 's/loglevel=3/loglevel=3 splash quiet/g' {} +
